blog/urls.py
# blog urls
from django.urls import path 
from blog import views


#for namespace
app_name = 'blog'

urlpatterns = [
    path('' , views.home , name = 'b-home'),
    path('post/<int:pk>' , views.detail_post , name = 'b-post'), # detail page + add comment form
    path('create-post/' , views.CreatePost.as_view() , name = 'b-create-post'),
    path('update-post/<int:pk>' , views.UpdatePost.as_view() , name = 'b-update-post'),
    path('delete-post/<int:pk>' , views.delete_post , name = 'b-delete-post'),
    path('delete-comment/<int:pk>' , views.delete_comment , name = 'b-delete-comment'),
    path('post/<int:pk>/like/' , views.like_post , name = 'b-like-post'),
    path('search/' , views.search , name = 'b-search')
]

marketplace/urls.py
# marketplace urls
from django.urls import path 
from marketplace import views

#for namespace
app_name = 'marketplace'

urlpatterns = [
    path('' , views.Products.as_view() , name = 'mp-home'),
    path('create/',views.CreateProduct.as_view(), name='mp-create'),
    path('product/<int:pk>/edit/',views.EditProduct.as_view(),name="mp-edit"),
    path('product/<int:pk>/',views.ProductDetails.as_view(), name='mp-details'),
    path('product/<int:pk>/delete/',views.DeleteProduct.as_view(),name='mp-delete'),
    path('search/',views.AnotherFilterView.as_view(),name="mp-search")
]

users/urls.py
# users urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path 
from users import views
from django.contrib.auth import views as auth_views

#for namespace
app_name = 'users'

urlpatterns = [
    # AUTH urls ------------------------------------------------------------------------------------------------------------
     path('' , views.home , name = 'u-home'),
     path('login/' , views.Login.as_view() , name = 'u-login'),
     path('logout/' , auth_views.LogoutView.as_view(next_page="user:u-home") , name = 'u-logout'),
     path('register/' , views.Register.as_view() , name='u-register'),
               # --------- password reset urls ---------
     path('password-reset/', views.custom_password_reset ,name='password_reset'),
     path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password-reset-done.html'),
         name='password_reset_done'),
     path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),
    # + another auth url path in route url file
               # ----------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
     # PROFILE urls ---------------------------------------------------------------------------------------------------------
     path('profile/<str:username>' , views.profile , name='u-profile'),
     path('update-profile/<int:pk>' , views.UpdateProfile.as_view() , name='u-update-profile'),
                        # --------- friends stuff urls --------- 
     path('send-friend-request/<int:pk>' , views.send_friend_request , name="u-send-friend-request"),
     path('accept-friend-request/<int:pk>' , views.accept_friend_request , name='u-accept-friend-request'),
     path('remove-friend/<int:pk>' , views.remove_friend , name='u-remove-friend'),
     path('friend-requests-list/<str:username>' , views.friend_requests_list , name='u-friend-requests-list'),
     path('friends-list/<str:username>' , views.friends_list , name='u-friends-list'),
                        # --------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_dev_project_l2/urls.py
from django.contrib import admin
from django.urls import path , include
# -- our urls
from blog import urls as blog_urls
from marketplace import urls as marketplace_urls
from users import urls as users_urls

from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(users_urls, namespace="user")),
    path('blog/', include(blog_urls,namespace="blog")),
    path('marketplace/', include(marketplace_urls,namespace="marketplace")),
    # path for users app
    path('password-reset-complete/', 
         PasswordResetCompleteView.as_view(template_name='users/password-reset-complete.html') , 
         name="password_reset_complete"),
]

marketplace/models.py
from django.db import models

from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
def product_directory_path(instancce,filename):
    return f"products/{instancce}/{filename}"

class Category(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Product(models.Model):
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    label = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    phone = PhoneNumberField()
    image = models.ImageField(upload_to=product_directory_path , blank=True)
    description = models.TextField(max_length=200)
    quantity = models.PositiveBigIntegerField(default=0)
    created_date = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, blank=True,null=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.label

marketplace/forms.py
from django import forms
from .models import Product,Category

class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['label', 'price', 'description','quantity','phone','image' , 'category']
        
class SearchProductsForm(forms.Form):
    name = forms.CharField(max_length=100,required=False )
    category = forms.ModelChoiceField(queryset=Category.objects.all(), empty_label="Select category" , required=False )
    max_price = forms.IntegerField(min_value=0, label='Maximum Price' )
    

marketplace/views.py
# marketplace views
from django.shortcuts import render
from django.urls import reverse_lazy
from .models import Product
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView,DeleteView,UpdateView,ListView,View
from .forms import CreateProductForm,SearchProductsForm
from django.db.models import Q

# Create your views here.
class Products(LoginRequiredMixin,ListView):
    model = Product
    template_name = 'marketplace/index.html' 
    context_object_name = 'products' 
    ordering = ['-created_date']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = SearchProductsForm()
        return context
    

class ProductDetails(LoginRequiredMixin,DeleteView):
    model = Product
    template_name = "marketplace/product_detail.html"
    context_object_name = 'product'


class CreateProduct(LoginRequiredMixin,CreateView):
    model = Product
    form_class = CreateProductForm
    template_name = "marketplace/create_product.html"
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    def get_success_url(self) -> str:
        return reverse_lazy('marketplace:mp-home')
    

class EditProduct(LoginRequiredMixin,UpdateView):
    model = Product
    form_class = CreateProductForm
    template_name = "marketplace/edit_product.html"
    
    def get_queryset(self):
        queryset = Product.objects.filter(user=self.request.user)
        return queryset
    
    def get_success_url(self):
        return reverse_lazy("marketplace:mp-details",kwargs={"pk":self.object.pk})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = self.get_object() 
        return context
    
class DeleteProduct(LoginRequiredMixin,DeleteView):
    model = Product
    template_name = "marketplace/delete_product.html"
    context_object_name = "product"

    def get_queryset(self):
        queryset = Product.objects.filter(user=self.request.user)

        return queryset
    def get_success_url(self):
        return reverse_lazy("marketplace:mp-home")
    
  

class AnotherFilterView(LoginRequiredMixin , View):
    def get(self , request):
        category = request.GET['category']
        max_price = request.GET['max_price']
        name = request.GET['name']
        filter_criteria = Q() 

        if category:
            filter_criteria &= Q(category=category)

        if max_price:
                filter_criteria &= Q(price__lte=max_price)

        if name:
                filter_criteria &= (Q(label__icontains=name) | Q(description__icontains=name))

        filtered_products = Product.objects.filter(filter_criteria)  # Apply filters to the Product queryset

        form = SearchProductsForm()
        return render(request, 'marketplace/index.html', {'products': filtered_products, 'form': form})

marketplace/templates/marketplace/create_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/marketplace/product-form.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <title>Fakebook | Add Product</title>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">F</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>

            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></a>
            </li>

            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>

            </div>
        </ul>
    </div>
    <h1>Add Product</h1>
    
    <form method="post" enctype="multipart/form-data" class="formm">
       {% csrf_token %}
        <label for="text">Label:</label>
        <textarea type="text" id="title" name="label" placeholder="Label" required></textarea>

        <label for="content">Description:</label>
        <textarea id="content" name="description" placeholder="Description ....." ></textarea>

        <label for="text">Phone:</label>
        <textarea type="text" id="title" name="phone" placeholder="+213" required></textarea>

        <label for="text">Price:</label>
        <textarea type="text" id="title" name="price" placeholder="Price" required></textarea>

        <label for="text">Quantity:</label>
        <textarea type="text" id="title" name="quantity" placeholder="Quantity" required></textarea>

        <label for="text">Category:</label>
        <select class="mp-input" id="cars" name="category">
            <option value="" selected disabled>Select category</option>
            {% for category in form.category.field.queryset %}
            <option value="{{ category.pk }}">{{ category }}</option>
            {% endfor %}
        </select>
    
        <label for="image">Image:</label>
        <input type="file" id="image" name="image" accept="image/*" required>
    
        <input type="submit" value="Add Product">
    </form>
    {% if form.errors %}
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <h3> - {{error}}</h3>
            {% endfor %}
        {% endfor %}
    {% endif %}
    </body>
    </html>

marketplace/templates/marketplace/delete_product.html
<!DOCTYPE html>
<html>
<head>
    <title>Delete Product</title>
</head>
<body>
    <h1>Delete Product</h1>
    <p>Are you sure you want to delete the product "{{ product.label }}"?</p>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'marketplace:mp-home' %}">Cancel</a>
    </form>
</body>
</html>

marketplace/templates/marketplace/edit_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">  
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/marketplace/product-form.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <title>Fakebook | Edit Product</title>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">F</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>

            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></a>
            </li>

            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>

            </div>
        </ul>
    </div>
    <h1>Edit Product</h1>
    
    <form method="post" enctype="multipart/form-data" class="formm">
       {% csrf_token %}
        <label for="text">Label:</label>
        <textarea type="text" id="title" name="label" placeholder="Label" required> {{product.label}} </textarea>

        <label for="content">Description:</label>
        <textarea id="content" name="description" placeholder="Description ....." > {{product.description}}  </textarea>

        <label for="text">Phone:</label>
        <textarea type="text" id="title" name="phone" placeholder="+213" required> {{product.phone}}  </textarea>

        <label for="text">Price:</label>
        <textarea type="text" id="title" name="price" placeholder="Price" required> {{product.price}}  </textarea>

        <label for="text">Quantity:</label>
        <textarea type="text" id="title" name="quantity" placeholder="Quantity" required> {{product.quantity}}  </textarea>

        <label for="text">Category:</label>
        <select class="mp-input" id="cars" name="category">
            <option value="{{product.category.id}}" selected disabled>{{product.category.name}} </option>
            {% for category in form.category.field.queryset %}
            <option value="{{ category.pk }}">{{ category }}</option>
            {% endfor %}
        </select>
    
        <label for="image">update current image:</label>
        <input type="file" id="image" name="image" accept="image/*" >
    
        <input type="submit" value="Edit Product">
    </form>
    {% if form.errors %}
        {% for field, errors in form.errors.items %}
            {% for error in errors %}
            <h3> - {{error}}</h3>
            {% endfor %}
        {% endfor %}
    {% endif %}
    </body>
    </html>

marketplace/templates/marketplace/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/marketplace/index.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <title> Fakebook | marketplace </title>
</head>
<body>
    <!-- navbar -->
    <div  class="navbar" style="height: 50px;">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">F</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>


            <div class="links">

            <li id="search" >
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>

            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></a>
            </li>

            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>

            </div>
        </ul>
    </div>
    <!-- end navbar -->

    <div class="container">
        <!-- side navbar -->
        <ul class="nav2">
            <a href="{% url 'user:u-friends-list' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-people-line" style="color: #74C0FC;"></i>Friends</button></li></a>
            <a href="{% url 'user:u-profile' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-user" style="color: #74C0FC;"></i>Profile</button></li></a>
            <a href="{% url 'marketplace:mp-home' %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-shop" style="color: #74C0FC;"></i>Marketplace</button></li></a>
        </ul>
        <!-- end side navbar -->
        <div class="filter-container">
            <form method="get" action="{% url 'marketplace:mp-search' %}">
                <input class="mp-input" type="text" placeholder="item name" name="name">
                <input class="mp-input" type="number" min="0" placeholder="max price" name="max_price">
                <select class="mp-input" id="cars" name="category">
                    <option value="" selected disabled>Select category</option>
                    {% for category in form.category.field.queryset %}
                    <option value="{{ category.pk }}">{{ category }}</option>
                    {% endfor %}
                </select>
                <input class="mp-submit" type="submit" value="Search">
            </form>
        </div>
        <a href={% url 'marketplace:mp-create' %}><button class="mp-submit" style="margin-bottom:20px;"> Add Product </button></a>
        <div class="products-container">
        {% if products %}
            {% for product in products %}
            <div class="product">

                <a href="{% url 'user:u-profile' product.user.username %}">
                <div class="card-header">
                    <div class="pfp-container">
                        <img class="pfp" src="{{product.user.profile.picture.url}}" alt="user pfp">
                    </div>
                    <p class="username">{{product.user.username}}</p>
                </div>
                </a>

                {% if product.image %}
                <div class="card-content">
                    <img src="{{product.image.url}}" alt="product image">
                </div>
                {% endif %}
                <a href="{% url 'marketplace:mp-details' product.id %}" style="color:black;">
                <div class="card-footer">
                        <p class="product-name">{{product.label}}</p>
                        <p class="description">{{product.description}}</p>
                        <p class="price">{{product.price}} Da</p>
                        <p>{{product.quantity}} piece </p>
                        <p>Category : {{product.category.name}}</p>
                       <div class="phone-container">
                        <p class="phone">Phone:{{product.phone}}</p>    
                       </div>            
                </div>
                </a>
            </div>
            {% endfor %} <!-- end product -->
        {% else %}
        <center> <h3> No products available 😦 </h3> </center>
        {% endif %}
        </div>
    </div>
</body>
</html>

marketplace/templates/marketplace/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{product.label}}</p>
    <p>{{profile.about}}</p>
    
</body>
</html>

marketplace/templates/marketplace/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% csrf_token%}
    <form method="get">
        {{form.as_p}}
        <input type="submit" value="search" >
    </form>
    

    {% for product in filtered_products %}
        {{product.label}}
    {% endfor %}
</body>
</html>