blog/urls.py
# blog urls
from django.urls import path 
from blog import views


#for namespace
app_name = 'blog'

urlpatterns = [
    path('' , views.home , name = 'b-home'),
    path('post/<int:pk>' , views.detail_post , name = 'b-post'), # detail page + add comment form
    path('create-post/' , views.CreatePost.as_view() , name = 'b-create-post'),
    path('update-post/<int:pk>' , views.UpdatePost.as_view() , name = 'b-update-post'),
    path('delete-post/<int:pk>' , views.delete_post , name = 'b-delete-post'),
    path('delete-comment/<int:pk>' , views.delete_comment , name = 'b-delete-comment'),
    path('post/<int:pk>/like/' , views.like_post , name = 'b-like-post'),
    path('search/' , views.search , name = 'b-search')
]

marketplace/urls.py
# marketplace urls
from django.urls import path 
from marketplace import views

#for namespace
app_name = 'marketplace'

urlpatterns = [
    path('' , views.Products.as_view() , name = 'mp-home'),
    path('create/',views.CreateProduct.as_view(), name='mp-create'),
    path('product/<int:pk>/edit/',views.EditProduct.as_view(),name="mp-edit"),
    path('product/<int:pk>/',views.ProductDetails.as_view(), name='mp-details'),
    path('product/<int:pk>/delete/',views.DeleteProduct.as_view(),name='mp-delete'),
    path('search/',views.AnotherFilterView.as_view(),name="mp-search")
]

users/urls.py
# users urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path 
from users import views
from django.contrib.auth import views as auth_views

#for namespace
app_name = 'users'

urlpatterns = [
    # AUTH urls ------------------------------------------------------------------------------------------------------------
     path('' , views.home , name = 'u-home'),
     path('login/' , views.Login.as_view() , name = 'u-login'),
     path('logout/' , auth_views.LogoutView.as_view(next_page="user:u-home") , name = 'u-logout'),
     path('register/' , views.Register.as_view() , name='u-register'),
               # --------- password reset urls ---------
     path('password-reset/', views.custom_password_reset ,name='password_reset'),
     path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password-reset-done.html'),
         name='password_reset_done'),
     path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),
    # + another auth url path in route url file
               # ----------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
     # PROFILE urls ---------------------------------------------------------------------------------------------------------
     path('profile/<str:username>' , views.profile , name='u-profile'),
     path('update-profile/<int:pk>' , views.UpdateProfile.as_view() , name='u-update-profile'),
                        # --------- friends stuff urls --------- 
     path('send-friend-request/<int:pk>' , views.send_friend_request , name="u-send-friend-request"),
     path('accept-friend-request/<int:pk>' , views.accept_friend_request , name='u-accept-friend-request'),
     path('remove-friend/<int:pk>' , views.remove_friend , name='u-remove-friend'),
     path('friend-requests-list/<str:username>' , views.friend_requests_list , name='u-friend-requests-list'),
     path('friends-list/<str:username>' , views.friends_list , name='u-friends-list'),
                        # --------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_dev_project_l2/urls.py
from django.contrib import admin
from django.urls import path , include
# -- our urls
from blog import urls as blog_urls
from marketplace import urls as marketplace_urls
from users import urls as users_urls

from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(users_urls, namespace="user")),
    path('blog/', include(blog_urls,namespace="blog")),
    path('marketplace/', include(marketplace_urls,namespace="marketplace")),
    # path for users app
    path('password-reset-complete/', 
         PasswordResetCompleteView.as_view(template_name='users/password-reset-complete.html') , 
         name="password_reset_complete"),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User , on_delete=models.CASCADE , related_name="posts")
    title = models.CharField(max_length=80)
    content = models.TextField(blank=True , null=True)
    image = models.ImageField(upload_to="posts_images" , blank=True , null=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} by {self.author.username} | {self.created_date}"
    
    #compress the image 
    def save(self , *args , **kwargs):
        super().save()
        if self.image:
            image = Image.open(self.image.path)
            if image.height > 700 or image.width > 700:
                image.thumbnail((700 , 700))
                image.save(self.image.path)



class PostComment(models.Model):
    author = models.ForeignKey(User , on_delete=models.CASCADE , related_name="post_comments")
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name="comments")
    comment = models.CharField(max_length=1200)


class PostLikes(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE , related_name="liked_posts")
    post = models.ForeignKey(Post , on_delete=models.CASCADE , related_name="likes")
    time = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = [('post' , 'user')]

blog/forms.py
from django import forms
from .models import Post , PostComment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title' , 'content' , 'image']
        widgets = {
            'content':forms.Textarea(attrs={'rows':20,'cols':100})
        }

class PostCommentForm(forms.ModelForm):
    class Meta:
        model = PostComment
        fields = ['comment']
        widgets = {
            'comment':forms.Textarea(attrs={'rows':10,'cols':70})
        }

blog/views.py
# blog views
from django.shortcuts import render , redirect , get_object_or_404
from .models import Post , PostComment , PostLikes
from django.contrib.auth.models import User
from .forms import PostForm , PostCommentForm
from django.views.generic import CreateView , UpdateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse , reverse_lazy
from django.db.models import Q

# Create your views here.

@login_required
def home(request):
    posts = Post.objects.all().order_by('-created_date')
    user = request.user
    friends = user.profile.friends.all()
    return render(request , 'blog/index.html' , {'posts':posts , 'friends':friends} )

@login_required
def search(request):
    if 'query' in request.GET and request.GET['query']:
        query = request.GET['query']
        posts = Post.objects.filter(Q(title__icontains = query) | Q(content__icontains = query) )
        users = User.objects.filter(username__icontains = query)
        friends = request.user.profile.friends.all()
        context = {'posts':posts , 'users':users , 'friends':friends}
        return render(request , 'blog/search.html' , context)
    else:
        return redirect('blog:b-home')

@login_required
def detail_post(request , pk):
    post = Post.objects.get(id=pk)
    user_has_liked = PostLikes.objects.filter(user=request.user , post=post)
    comments = PostComment.objects.filter(post=post)
    # add a new comment to the post from the same view 
    if request.method == 'POST':
        form = PostCommentForm(request.POST)
        if form.is_valid:
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
    
    context = {'post':post , 'form':PostCommentForm() , 'comments':comments , 'user_has_liked':user_has_liked}
    return render(request , 'blog/post.html' , context)

class CreatePost(LoginRequiredMixin , CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/create-post.html'

    def form_valid(self, form):
        post = form.save(commit=False)   
        post.author = self.request.user
        post.save()
        return HttpResponseRedirect(reverse_lazy('blog:b-home'))
    

class UpdatePost(LoginRequiredMixin , UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/update-post.html'

    def get_success_url(self):
        return reverse_lazy('blog:b-post' , kwargs={'pk':self.kwargs['pk']})

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = self.get_object()  
        return context
    

@login_required   
def delete_post(request , pk):
    post = Post.objects.filter(Q(author=request.user) & Q(id=pk))
    post.delete()
    return redirect('blog:b-home')


@login_required
def delete_comment(request , pk):
    comment = PostComment.objects.get(Q(author=request.user) & Q(id=pk))
    pk = comment.post.id
    comment.delete()
    return redirect(reverse('blog:b-post' , kwargs={'pk':pk}))


@login_required
def like_post(request , pk):
    post = get_object_or_404(Post , id=pk)
    user = request.user
    
    if PostLikes.objects.filter(post=post , user=user).exists(): # then remove the like
        PostLikes.objects.filter(post=post , user=user).delete()
    else: # else like
        PostLikes.objects.create(user=user, post=post)

    return redirect(reverse('blog:b-post' , kwargs={'pk':pk}))

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fakebook | Blog</title>
    <link rel="stylesheet" href="{% static 'styles/blog/index.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">f</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>
            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
            </li>
            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>
            </div>
        </ul>
    </div>

<div class="home-container">
        
    <ul class="nav2">
        <a href="{% url 'user:u-friends-list' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-people-line" style="color: #74C0FC;"></i>Friends</button></li></a>
        <a href="{% url 'user:u-profile' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-user" style="color: #74C0FC;"></i>Profile</button></li></a>
        <a href="{% url 'marketplace:mp-home' %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-shop" style="color: #74C0FC;"></i>Marketplace</button></li></a>
    </ul>

    <div class="posts-contianer">

        <a href="{% url 'blog:b-create-post' %}"> <div class="add-post">
            <div class="part-1">
                <img  class="img-pro2 img-pro" src="{{user.profile.picture.url}}">
                <div style="margin-left: 20px;font-family: gg;"><p>{{user.username}}</p></div>
            </div>
            <div class="part-2">
                <p>what on your mind, {{user.username}} ?</p>
            </div>
            <div class="part-3">
                <p>Photo</p>
                <p>Feeling/Activity</p>
            </div>
        </div>
        </a>

        <div style="display: flex;flex-direction: column;">

            {% if posts %}
            {% for post in posts %}
            <div class="the-post">

            <a href="{% url 'user:u-profile' post.author.username %}">
            <div class="main-post-1">
                <img class="img-pro2 img-pro" src="{{post.author.profile.picture.url}}">
                <div class="details-post">
                    <div class="nameus"><p style="margin-bottom: 0px;">{{post.author.username}}</p></div>
                    <div class="date-post">{{post.created_date}}</div> 
                </div>
            </div>
            </a>

            <a href="{% url 'blog:b-post' post.id %}" class="a-post">

            <div class="main-post-2">
                <h2 class="disc">{{post.title}}</h2>
                {% if post.content %}
                <p class="disc">{{post.content|linebreaksbr}}</p>
                {% endif %}
            </div>

            <div  class="main-post-3">
                {% if post.image %}
                <img class="post-photo" src="{{post.image.url}}" >
                {% endif %}
            </div>
            </a>
            <div class="main-post-4">
                <button class="bbb"> <p><i class="fa-regular fa-thumbs-up fa-lg" style="color: #74C0FC;"></i>Likes | {{post.likes.count}}</p></button>
                <button class="bbb"> <p><i class="fa-regular fa-comment fa-lg" style="color: #74C0FC;"></i>Comments | {{post.comments.count}}</p></button>
            </div>


            </div>
            {% endfor %}
            {% else %} <!-- if no posts -->
            <h3>no posts available</h3>
            {% endif %}
            
        </div>
        

    </div>
    <div class="hh" style="display: flex; flex-direction: column;width: 20%;margin-left:60px;">
        <div style="padding-bottom: 10px;">
            <img style="height: 190px;" src="https://cdn.discordapp.com/attachments/1096118526361739286/1224841412479160461/Fiverr-1.png?ex=661ef575&is=660c8075&hm=1c900e071b231249b68236d745aa8cd65b438ec65fa9436e22b05d2d84596854&" alt="">
        </div>
    <div class="friends">
        <div>
            <p>Your Friends :</p>
        </div>

        {% if friends %}
        {% for friend in friends %}
        <div style="display: flex; flex-direction: row; gap: 5px; margin-bottom: 20px;">
            <div >
                <img style="margin: 0px;" class="img-pro" src="{{friend.profile.picture.url}}" alt="">
            </div>
            <div >
                <p style="margin: 0%; font-size: 20px;">{{friend.username}}</p>
            </div>
            <div >
                <a href=""><i  class="msg fa-regular fa-message fa-sm"></i> </a>
            </div>
        </div>
        {% endfor %}
        {% endif %}

    </div>
    </div>

</div>
    
</body>
</html>

blog/templates/blog/post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'styles/blog/post.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f"><i>f</i></div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>
            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
            </li>
            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>
            </div>
        </ul>
    </div>

<div class="home-container">
        
    <ul class="nav2">
        <a href="{% url 'user:u-friends-list' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-people-line" style="color: #74C0FC;"></i>Friends</button></li></a>
        <a href="{% url 'user:u-profile' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-user" style="color: #74C0FC;"></i>Profile</button></li></a>
        <a href="{% url 'marketplace:mp-home' %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-shop" style="color: #74C0FC;"></i>Marketplace</button></li></a>
    </ul>

    <div class="posts-contianer">
        <div style="display: flex;flex-direction: column;">
            <div class="the-post">
                <div class="main-post-1">
                    <img class="img-pro2 img-pro" src="{{post.author.profile.picture.url}}">
                    <div class="details-post">
                        <div class="nameus"><p style="margin-bottom: 0px;">{{post.author.username}}</p></div>
                        <div class="date-post">{{post.created_date}}</div> 
                    </div>
                    {% if post.author == user %}
                    <div class="admin">
                        <a href="{% url 'blog:b-update-post' post.id %}"><button class="edit">Edit</button></a>
                        <a href="{% url 'blog:b-delete-post' post.id %}"><button class="delete">Delete</button></a>
                    </div>
                    {% endif %}
                </div>
                <div class="main-post-2">
                    <h3 class="disc">{{post.title}}</h3>
                    {% if post.content %}
                    <p class="disc">{{post.content}}</p>
                    {% endif %}
                </div>
                {% if post.image %}
                <div  class="main-post-3">
                    <img class="post-photo" src="{{post.image.url}}" >
                </div>
                {% endif %}
                <div class="main-post-4">
                    {% if not user_has_liked %}
                    <button class="bbb"> <p>
                    <a href="{% url 'blog:b-like-post' post.id %}" style="color:black;">
                        <i class="fa-regular fa-thumbs-up fa-lg" style="color: #74C0FC;"></i>Like | {{post.likes.count}}
                    </a>
                    </p></button>
                    {% else %}
                    <button class="bbb"> <p>
                        <a href="{% url 'blog:b-like-post' post.id %}" style="color:black;">
                            <i class="fa-regular fa-thumbs-up fa-lg" style="color: #74C0FC;"></i>Remove Like | {{post.likes.count}}
                        </a>
                    </p></button>
                    {% endif %}
                    <button class="bbb"> <p><i class="fa-regular fa-comment fa-lg" style="color: #74C0FC;"></i>Comment | {{post.comments.count}}</p></button>
                </div>
                <div class="comment-container">
                    <form class="comnt-form" method="POST">
                        {% csrf_token %}
                        <div style="display: flex; flex-direction: row; gap: 5px; width: 160px;">
                            <div >
                                <img style="margin: 0px;" src="{{user.profile.picture.url}}" class="img-pro">
                            </div>
                            <div >
                                <p style="margin: 0%; font-size: 20px;">{{user.username}}</p>
                            </div>
                        </div>
                        <input class="input" type="text" name="comment"  placeholder="What are you thinking...">
                    </form>
                    
                    <div class="comments">
                        {% if comments %}
                        {% for comment in comments %}
                        <div class="comnt">
                            <div style="display: flex; flex-direction: row; gap: 5px;">
                                <div style="display: flex; flex-direction: row; gap: 5px; width: 160px;">
                                    <a href={% url 'user:u-profile' comment.author.username %} style="color:black; display:flex;">
                                    <div >
                                        <img style="margin: 4px;" class="img-pro" src="{{comment.author.profile.picture.url}}" alt="">
                                    </div>

                                    <div>
                                        <p style="margin: 0%; font-size: 20px;">{{comment.author.username}}</p>
                                    </div>
                                    </a>
                                </div>
                                {% if comment.author == user %}
                                <a href="{% url 'blog:b-delete-comment' comment.id %}">
                                <button style="background-color: white; border-width: 0px; margin-left: auto;cursor: pointer;">X</button>
                                </a>
                                {% endif %}
                            </div>
                            <p style="background-color: #ececec; padding: 10px; border-radius: 8px;">{{comment.comment|linebreaksbr}}</p>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        

    </div>
    <div class="hh" style="display: flex; flex-direction: column;width: 20%;margin-left:60px;">
        <div style="padding-bottom: 10px;">
            <img style="height: 190px;" src="https://cdn.discordapp.com/attachments/1096118526361739286/1224841412479160461/Fiverr-1.png?ex=661ef575&is=660c8075&hm=1c900e071b231249b68236d745aa8cd65b438ec65fa9436e22b05d2d84596854&" alt="">
        </div>
    <div class="friends">
        <div>
            <p>Your Friends :</p>
        </div>
        <div style="display: flex; flex-direction: row; gap: 5px; margin-bottom: 20px;">
        {% if friends %}
        {% for friend in friends %}
        <div style="display: flex; flex-direction: row; gap: 5px; margin-bottom: 20px;">
            <div >
                <img style="margin: 0px;" class="img-pro" src="{{friend.profile.picture.url}}" alt="">
            </div>
            <div >
                <p style="margin: 0%; font-size: 20px;">{{friend.username}}</p>
            </div>
            <div >
                <a href=""><i  class="msg fa-regular fa-message fa-sm"></i> </a>
            </div>
        </div>
        {% endfor %}
        {% endif %}
        </div>
    </div>
    </div>

</div>
    
</body>
</html>

blog/templates/blog/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Fakebook | Search </title>
    <link rel="stylesheet" href="{% static 'styles/blog/search.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">f</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>
            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
            </li>
            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>
            </div>
        </ul>
    </div>

<div class="home-container">
        
    <ul class="nav2">
        <a href="{% url 'user:u-friends-list' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-people-line" style="color: #74C0FC;"></i>Friends</button></li></a>
        <a href="{% url 'user:u-profile' user.username %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-user" style="color: #74C0FC;"></i>Profile</button></li></a>
        <a href="{% url 'marketplace:mp-home' %}"> <li class="li-list"><button class="bbb"><i class="fa-solid fa-shop" style="color: #74C0FC;"></i>Marketplace</button></li></a>
    </ul>


    <div class="posts-contianer">
        <div class="ppl">
            <p style="padding: 10px; margin: 0px; font-weight: bold;font-size: 30px;">People :</p>
        </div>
        {% if users %}
        {% for usr in users %}
            <div style="display: flex; flex-direction: row; gap: 30px; margin-bottom: 20px;border-bottom: 1px solid gray;">
                <div >
                    <img style="margin: 0px;" class="img-pro" src="{{usr.profile.picture.url}}" alt="">
                </div>
                <a href="{% url 'user:u-profile' usr.username %}" style="text-decoration:none; color:black;">
                <div >
                    <p style="margin: 0%; font-size: 20px;">{{usr.username}}</p>
                </div>
                </a>
                <div >
                    <a href="{% url 'user:u-send-friend-request' usr.id %}"><i class="fa-solid fa-plus" style="color: #74C0FC;"></i> </a>
                </div>
            </div>
        {% endfor %}
        {% else %}
        <h3>No users match your search</h3>
        {% endif %}

        
        <div class="ppl">
            <p style="padding: 10px; margin: 0px; font-weight: bold;font-size: 30px;">Posts :</p>
        </div>

        {% if posts %}

        <div style="display: flex;flex-direction: column;">
        {% for post in posts %}
        <a href="{% url 'blog:b-post' post.id %}" style="text-decoration:none; color:black;">
        <div class="the-post">
            <div class="main-post-1">
                <img class="img-pro2 img-pro" src="{{ post.author.profile.picture.url }}">
                <div class="details-post">
                    <div class="nameus"><p style="margin-bottom: 0px;">{{ post.author.username }}</p></div>
                    <div class="date-post">{{ post.created_date }}</div> 
                </div>
            </div>
            <div class="main-post-2">
                <h2> {{ post.title }} </h2>
                {% if post.content %}
                <p class="disc">{{ post.content|linebreaksbr  }}</p>
                {% endif %}
            </div>
            <div  class="main-post-3">
                <img class="post-photo" src="{{ post.image.url }}" >
            </div>
            <div class="main-post-4">
                <button class="bbb"> <p><i class="fa-regular fa-thumbs-up fa-lg" style="color: #74C0FC;"></i>Like | {{post.likes.count}}</p></button>
                <button class="bbb"> <p><i class="fa-regular fa-comment fa-lg" style="color: #74C0FC;"></i>Comment | {{post.comments.count}}</p></button>
            </div>
        </div>
        </a>
        {% endfor %}
        </div>

        {% else %}
        <h3>No user username matches your search</h3>
        {% endif %}
        

    </div>
    <div class="hh" style="display: flex; flex-direction: column;width: 20%;margin-left:60px;">
        <div style="padding-bottom: 10px;">
            <img style="height: 190px;" src="https://cdn.discordapp.com/attachments/1096118526361739286/1224841412479160461/Fiverr-1.png?ex=661ef575&is=660c8075&hm=1c900e071b231249b68236d745aa8cd65b438ec65fa9436e22b05d2d84596854&" alt="">
        </div>
    <div class="friends">
        <div>
            <p>Your Friends :</p>
        </div>
        {% if friends %}
        {% for friend in friends %}
        <div style="display: flex; flex-direction: row; gap: 5px; margin-bottom: 20px;">
            <div >
                <img style="margin: 0px;" class="img-pro" src="{{friend.profile.picture.url}}" alt="">
            </div>
            <div >
                <p style="margin: 0%; font-size: 20px;">{{friend.username}}</p>
            </div>
            <div >
                <a href=""><i  class="msg fa-regular fa-message fa-sm"></i> </a>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    </div>

</div>
    
</body>
</html>