blog/urls.py
# blog urls
from django.urls import path 
from blog import views


#for namespace
app_name = 'blog'

urlpatterns = [
    path('' , views.home , name = 'b-home'),
    path('post/<int:pk>' , views.detail_post , name = 'b-post'), # detail page + add comment form
    path('create-post/' , views.CreatePost.as_view() , name = 'b-create-post'),
    path('update-post/<int:pk>' , views.UpdatePost.as_view() , name = 'b-update-post'),
    path('delete-post/<int:pk>' , views.delete_post , name = 'b-delete-post'),
    path('delete-comment/<int:pk>' , views.delete_comment , name = 'b-delete-comment'),
    path('post/<int:pk>/like/' , views.like_post , name = 'b-like-post'),
    path('search/' , views.search , name = 'b-search')
]

marketplace/urls.py
# marketplace urls
from django.urls import path 
from marketplace import views

#for namespace
app_name = 'marketplace'

urlpatterns = [
    path('' , views.Products.as_view() , name = 'mp-home'),
    path('create/',views.CreateProduct.as_view(), name='mp-create'),
    path('product/<int:pk>/edit/',views.EditProduct.as_view(),name="mp-edit"),
    path('product/<int:pk>/',views.ProductDetails.as_view(), name='mp-details'),
    path('product/<int:pk>/delete/',views.DeleteProduct.as_view(),name='mp-delete'),
    path('search/',views.AnotherFilterView.as_view(),name="mp-search")
]

users/urls.py
# users urls
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path 
from users import views
from django.contrib.auth import views as auth_views

#for namespace
app_name = 'users'

urlpatterns = [
    # AUTH urls ------------------------------------------------------------------------------------------------------------
     path('' , views.home , name = 'u-home'),
     path('login/' , views.Login.as_view() , name = 'u-login'),
     path('logout/' , auth_views.LogoutView.as_view(next_page="user:u-home") , name = 'u-logout'),
     path('register/' , views.Register.as_view() , name='u-register'),
               # --------- password reset urls ---------
     path('password-reset/', views.custom_password_reset ,name='password_reset'),
     path('password-reset-done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password-reset-done.html'),
         name='password_reset_done'),
     path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password-reset-confirm.html'),
         name='password_reset_confirm'),
    # + another auth url path in route url file
               # ----------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
     # PROFILE urls ---------------------------------------------------------------------------------------------------------
     path('profile/<str:username>' , views.profile , name='u-profile'),
     path('update-profile/<int:pk>' , views.UpdateProfile.as_view() , name='u-update-profile'),
                        # --------- friends stuff urls --------- 
     path('send-friend-request/<int:pk>' , views.send_friend_request , name="u-send-friend-request"),
     path('accept-friend-request/<int:pk>' , views.accept_friend_request , name='u-accept-friend-request'),
     path('remove-friend/<int:pk>' , views.remove_friend , name='u-remove-friend'),
     path('friend-requests-list/<str:username>' , views.friend_requests_list , name='u-friend-requests-list'),
     path('friends-list/<str:username>' , views.friends_list , name='u-friends-list'),
                        # --------------------------------------
     # ----------------------------------------------------------------------------------------------------------------------
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_dev_project_l2/urls.py
from django.contrib import admin
from django.urls import path , include
# -- our urls
from blog import urls as blog_urls
from marketplace import urls as marketplace_urls
from users import urls as users_urls

from django.contrib.auth.views import PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(users_urls, namespace="user")),
    path('blog/', include(blog_urls,namespace="blog")),
    path('marketplace/', include(marketplace_urls,namespace="marketplace")),
    # path for users app
    path('password-reset-complete/', 
         PasswordResetCompleteView.as_view(template_name='users/password-reset-complete.html') , 
         name="password_reset_complete"),
]

users/models.py
from PIL import Image
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE , related_name='profile')
    about = models.CharField(max_length=850 , null=True , blank=True)
    picture = models.ImageField(upload_to='profile-pictures' , default ='profile-pictures/default.jpg')
    friends = models.ManyToManyField(User , related_name="friends" , blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'
    
    def save(self):
        super().save()
        img = Image.open(self.picture.path)
        # compress the profile picture
        if img.height > 300 or img.width > 300:
            img.thumbnail((300 , 300))
            img.save(self.picture.path)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(User , related_name="sent_friend_requests" , on_delete=models.CASCADE )
    to_user = models.ForeignKey(User , related_name="friend_requests" , on_delete=models.CASCADE )

users/forms.py
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserCreationFormCostum(UserCreationForm):
    email = forms.EmailField(required=True , label="Email")

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("about", "picture")
        widgets = {
            'about':forms.Textarea(attrs={'rows':10, 'cols':70})
            }

users/views.py
# users views
from django.http import HttpResponseRedirect , HttpResponse
from django.shortcuts import render , redirect , get_object_or_404
from django.urls import reverse_lazy 
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView , UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate , login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserCreationFormCostum , ProfileForm
from .models import Profile , FriendRequest

# imports for the custoum password reset view ---------
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
from django.core.mail import send_mail
# ---------------------------------------------------

# Create your views here.
def home(request):
    return redirect('blog:b-home')

# login view
class Login(LoginView):
    template_name = 'users/login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('blog:b-home')
    
# Register view
class Register(CreateView):
    template_name = 'users/register.html'
    model = User
    form_class = UserCreationFormCostum
    
    def form_valid(self, form):
        # Create a profile when a new user is created instead of using signals
        new_user = form.save()
        user_profile = Profile()
        user_profile.user = new_user
        user_profile.save()
        # authenticate the user and redirect him to a main page
        username = self.request.POST['username']
        password = self.request.POST['password1']
        user = authenticate(username=username , password=password)
        if user is not None:
            login(self.request , user)
            # send mail to user that he's now registered
            email_body = render(self.request, 'users/registered-email.txt', {
                            'user': user,
                        }).content.decode('utf-8')
            send_mail(
                        'Welcome to Fakebook 🚀',
                        email_body,
                        'fakebook.projet.l2@gmail.com', 
                        [user.email],
                        fail_silently=False,
                    )
        # redirect
        return HttpResponseRedirect(reverse_lazy('blog:b-home'))
    
# costum reset password view
def custom_password_reset(request):
    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            associated_users = User.objects.filter(email=email)
            if associated_users.exists():
                for user in associated_users:

                    uid = urlsafe_base64_encode(force_bytes(user.pk))
                    token = default_token_generator.make_token(user)

                    reset_url = f"{request.scheme}://{request.get_host()}/password-reset-confirm/{uid}/{token}"

                    email_subject = 'Reset Password on Fakebook'
                    email_body = render(request, 'users/password-reset-email.txt', {
                        'user': user,
                        'reset_url': reset_url,
                    }).content.decode('utf-8')
                    send_mail(
                        email_subject,
                        email_body,
                        'fakebook.projet.l2@gmail.com', 
                        [email],
                        fail_silently=False,
                    )

                return redirect('user:password_reset_done')
    else:
        form = PasswordResetForm()
    return render(request, 'users/password-reset.html', {'form': form})

# profile views
@login_required
def profile(request , username):
    user = User.objects.get(username=username)
    profile = Profile.objects.get(user=user)
    # check if user is friend with the profile user
    is_friend = profile.friends.contains(request.user)
    # we also gonna pass user posts in the context when the blog app is ready
    context = {'profile':profile , 'is_friend':is_friend}
    return render(request , 'users/profile.html' , context)


class UpdateProfile(LoginRequiredMixin , UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'users/profile-update.html'

    def get_success_url(self):
        profile_id = self.kwargs['pk']
        profile = Profile.objects.get(id=profile_id)
        username = profile.user.username
        return reverse_lazy('user:u-profile' , kwargs={'username':username})

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = self.get_object()  
        return context
    

# friends views

@login_required  
def send_friend_request(request, pk):
    user = request.user
    requested_user = get_object_or_404(User , id=pk)
    user_profile = Profile.objects.get(user=user)
    # if requested user is already a friend
    if user_profile.friends.contains(requested_user):
        return HttpResponse('requested user is already your friend!')
    # if friend request was already sent
    elif FriendRequest.objects.filter(from_user=user , to_user=requested_user).exists():
        return HttpResponse('friend request was already sent')
    else:
        friend_request = FriendRequest(from_user=user , to_user=requested_user)
        friend_request.save()
        return HttpResponseRedirect(reverse_lazy('user:u-profile' , kwargs = {'username':requested_user.username}))
    

@login_required
def accept_friend_request(request , pk):
    friend_request = FriendRequest.objects.get(id=pk)
    # if the request concern the user
    if friend_request.to_user == request.user:
        friend_request.from_user.profile.friends.add(friend_request.to_user)
        friend_request.to_user.profile.friends.add(friend_request.from_user)
        # delete the friend request 
        friend_request.delete()
        return HttpResponseRedirect(reverse_lazy('user:u-profile' , kwargs = {'username':request.user.username}))
    else:
        return HttpResponse('Error')
    

@login_required
def remove_friend(request , pk):
    friend = get_object_or_404(User , id=pk)
    user = request.user
    if user.profile.friends.contains(friend):
        user.profile.friends.remove(friend)
        friend.profile.friends.remove(user)
        return HttpResponseRedirect(reverse_lazy('user:u-profile' , kwargs = {'username':request.user.username}))
    else:
        return HttpResponse('Error: user was not found in your friends list')    

@login_required
def friend_requests_list(request , username):
    user = get_object_or_404(User, username=username)
    if user != request.user:
        return HttpResponse('Error occured')
    friend_requests = FriendRequest.objects.filter(to_user=user)
    context = {'requests':friend_requests}
    return render(request , 'users/friend-requests-list.html' , context)

@login_required
def friends_list(request , username):
    user = get_object_or_404(User, username=username)
    friends = user.profile.friends.all()
    context = {'friends':friends , 'this_user':user}
    return render(request , 'users/friends-list.html' , context)

users/templates/users/friend-requests-list.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'styles/users/friends-list.css' %}">
    <title>Fakebook | Friend requests</title>
</head>
<body>

    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f"><i>f</i></div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>
  
            <li>
              <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
            </li>
  
             <li>
              <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>
  
            </div>
        </ul>
    </div>

    <h2>You have {{ requests.count }} friend request</h2>
    {% if requests %}
        <div class="friends-container">
        {% for request in requests %}
            <div class="friend">
                <div class="friend-user-info">
                    <img src="{{ request.from_user.profile.picture.url }}" alt="User Picture">
                    <p>{{ request.from_user.username }}</p>
                </div>
                <div class="friend-buttons">
                    <a href="{% url 'user:u-accept-friend-request' request.id %}"><button>ACCEPT</button></a>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>No requests</h4>
    {% endif %}
</body>
</html>

users/templates/users/friends-list.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fakebook | Friends</title>
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'styles/users/friends-list.css' %}">
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f"><i>f</i></div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>
  
            <li>
              <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
            </li>
  
             <li>
              <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>
  
            </div>
        </ul>
    </div>

    {% if user == this_user %} <!---------------------------------------->

    <h2>Your friends</h2>
    {% if friends %}
        <div class="friends-container">
        {% for friend in friends %}
            <div class="friend">
                <!-- USER INFO -->
                <a href="{% url 'user:u-profile' friend.username %}">
                <div class="friend-user-info">
                    <img src="{{ friend.profile.picture.url }}" alt="User Picture">
                    <p>{{ friend.username }}</p>
                </div>
                </a>
                <!-- -------- -->
                <div class="friend-buttons">
                    <a href="{% url 'user:u-remove-friend' friend.id %}"><button>REMOVE</button></a>
                </div>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>You have 0 friends</h4>
    {% endif %}

    {% else %}  <!---------------------------------------->

    <h2>{{this_user.username}} friends</h2>
    {% if friends %}
        <div class="friends-container">
        {% for friend in friends %}
            <div class="friend">
                <!-- USER INFO -->
                <a href="{% url 'user:u-profile' friend.username %}">
                <div class="friend-user-info">
                    <img src="{{ friend.profile.picture.url }}" alt="User Picture">
                    <p>{{ friend.username }}</p>
                </div>
                </a>
            </div>
        {% endfor %}
        </div>
    {% else %}
        <h4>{{this_user.username}} have 0 friends</h4>
    {% endif %}

    {% endif %}  <!---------------------------------------->
</body>
</html>

users/templates/users/index.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Fakebook </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f2f5;
        }
    </style>
</head>
<body>
    {% if user.is_authenticated %}

    <!-- navbar for testing only , with simple css -->
    <div style="background-color: #007bff; padding: 10px;">
        <span style="font-size: 24px; color: #fff; margin-right: 20px;">Fakebook</span>
        <input type="text" placeholder="Search" style="padding: 5px; border-radius: 5px; border: none; margin-right: 20px;">
        <a href="{% url 'blog:b-home' %}" style="color: #fff; text-decoration: none; margin-right: 20px; transition: color 0.3s;">Blog</a>
        <a href="{% url 'marketplace:mp-home' %}" style="color: #fff; text-decoration: none; margin-right: 20px; transition: color 0.3s;">Marketplace</a>
        <a href="{% url 'user:u-profile' user.username %}" style="color: #fff; text-decoration: none; margin-right: 20px; transition: color 0.3s;">Profile</a>
        <a href="{% url 'user:u-logout' %}" style="color: #fff; text-decoration: none; transition: color 0.3s;">Logout</a>
    </div>
    <!------------------------------------------------>

    <h1> Logged in successfully </h1>
    <a href="{% url 'user:u-profile' user.username %}"><p>Your Profile</p></a>
    <a href="logout/"><p>logout</p></a>

    {% else %}
    <h1> You're not logged in </h1>
    <a href="login/"><p>login</p></a>
    <a href="register/"><p>Register</p></a>
    {% endif %}
</body>
</html>

users/templates/users/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fakebook | Sign in </title>
    <link rel="stylesheet" href="{% static 'styles/users/login.css' %}">

</head>
<body>
    <div class="container">
        <div class="sign-in-form">
            <form method = "POST">
                {%csrf_token%}
                <h1 id="sign-header"> Sign In</h1>
                <input type="text" id="username" placeholder="Username" required name="username">
                <input type="password" id="password" placeholder="Password" required name="password">
                <a href="{% url 'user:password_reset' %}" > Forget Your Password?</a>
                <input type="submit" value="SIGN IN" id="sign-in-butt" >
                {% if form.errors %}
                    <div class="error-message">
                        {% for field, error_list in form.errors.items %}
                            {% for error in error_list %}
                            {{ error }}
                            {% endfor %}
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>
        <div class="sign-up-form">
            <h1> Fakebook </h1>
            <h3> Connect with friends and the world around you on Fakebook. </h3>
            <p>Don't have an account? register now</p>
            <a href="{% url 'user:u-register' %}"><button id="sign-up-butt"> SIGN UP </button></a>
        </div>
    </div>
</body>
</html>

users/templates/users/password-reset-complete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fakebook | Reset password done </title>
    <link rel="stylesheet" href="{% static 'styles/users/password-reset.css' %}">
</head>
<body>
    <div class="container" styles="padding:30px;">
        <div class="sign-in-form">
            <h1>Password reset complete</h1>
            <p>Your new password has been set.<a href="{% url 'user:u-login' %}"> Login</a>.</p>
        </div>         
    </div>
</body>
</html>

users/templates/users/password-reset.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fakebook | Reset password </title>
    <link rel="stylesheet" href="{% static 'styles/users/password-reset.css' %}">
</head>
<body>
    <div class="container">
        <div class="sign-in-form">
            <form method="POST">
                {% csrf_token %}
                <h1>Find your account</h1>
                <span>Please enter your email to search for your account.</span>
                <input type="email" placeholder="Enter Your Email" name="email">
                <div style="display: flex;">
                    <a  href="{% url 'user:u-login' %}"><button type="button" id="cal-butt"> Cancel</button></a>
                    <input type="submit" id="sea-butt" value="Search">
                </div> 
            </form>    
        </div>         
    </div>
</body>
</html>

users/templates/users/profile-update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/users/update-profile.css' %}">
    <script src="https://kit.fontawesome.com/f8e3ad68c8.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/5665c51b75.js" crossorigin="anonymous"></script>
    <title>Fakebook | Update profile</title>
</head>
<body>
    <div style="height: 50px;" class="navbar">
        <ul class="nav1">
            <li>
                <div class="logo">
                    <div class="f">F</div>
                    <span style="margin-right: 10px;" class="book">ake book</span>
                    <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
                </div>
            </li>
            
            
            <div class="links">
            
            <li id="search">
                
                <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                    <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                    <input id="input-s" type="search" name="query" placeholder="Search">
                    <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                    </div>
                </form>
            </li>

            <li>
                <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></a>
            </li>

            <li>
                <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
            </li>

            </div>
        </ul>
    </div>
    <h1>Update Profile</h1>  
    
    <form method="post" enctype="multipart/form-data" class="formm">
        {% csrf_token %}

        <label for="content">About:</label>
        <textarea id="content" name="about" placeholder="Enter the content of your post" >{{ profile.about}}</textarea>
    
        <label for="image">Change Image:</label>
        <input type="file" id="image" name="image" accept="image/*" >
        <!-- If you want to show the current image -->
        <label for="image">Current image</label>
        <div class="image-preview">
            <img src="{{ profile.picture.url }}" alt="Current Image">
        </div>
    
        <input type="submit" value="Update Profile">
    </form>
    
    </body>
    </html>

users/templates/users/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fakebook | {{profile.user.username}}</title>
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
    />
    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'styles/users/profile.css' %}" />
  </head>
  <body>
    <div style="height: 50px;" class="navbar">
      <ul class="nav1">
          <li>
              <div class="logo">
                  <div class="f"><i>f</i></div>
                  <span style="margin-right: 10px;" class="book">ake book</span>
                  <a href="{% url 'blog:b-home' %}"><button class="btn notf"><i class="fa-solid fa-house"></i> </button></a>
              </div>
          </li>
          
          
          <div class="links">
          
          <li id="search">
              
              <form  action="{% url 'blog:b-search' %}" method="get" style="display: flex;">
                  <div style="background-color: white;display: flex;border-radius: 30px;width: 300px;">
                  <input id="input-s" type="search" name="query" placeholder="Search">
                  <button id="srch-btn" type="submit" value="Search"><i style="color: gray;" class="fa-solid fa-magnifying-glass fa-lg"></i></button>
                  </div>
              </form>
          </li>

          <li>
            <a href="{% url 'user:u-profile' user.username %}"><img class="img-pro" src="{{user.profile.picture.url}}"></button></a>
          </li>

           <li>
            <a href="{% url 'user:u-logout' %}"><button class=" btn logout"><i class="fa-solid fa-door-open fa-lg"></i></button></a>
          </li>

          </div>
      </ul>
  </div>
    <div class="header__wrapper" style="margin-top:150px">
      <div class="cols__container">
        <div class="left__col">
          <div class="img__container">
            <img src="{{profile.picture.url}}" alt="pfp" />
            <span></span>
          </div>
          <h2>{{profile.user.username}}</h2>
          <p>{{profile.about|linebreaksbr}}</p>

          <ul class="about">
            <li><span>{{profile.user.friends.count}}</span>Friends</li>
            <li><span>{{profile.user.posts.count}}</span>Posts</li>
          </ul>

          <div class="content">


            <ul>
              <li><i class="fab fa-twitter"></i></li>
              <i class="fab fa-instagram"></i>
              <i class="fab fa-snapchat"></i>
            </ul>
          </div>
        </div>
        <div class="right__col">
          <nav>
            <div class="button">
        
            {% if profile.user == user %}
            <a href="{% url 'user:u-update-profile' profile.user.id %}" class="update"><button>UPDATE</button></a>
            <a href="{% url 'user:u-friend-requests-list' profile.user.username %}" class="friend_request"><button>FRIENDS REQUEST</button></a>
            {% else %}
                {% if is_friend %}
                <a href="{% url 'user:u-remove-friend' profile.user.id %}" class="follow"><button>Remove friend</button></a>
                {% else %}
                <a href="{% url 'user:u-send-friend-request' profile.user.id %}" class="follow"><button>Send friend request</button></a>
                {% endif %}
            {% endif %}
            <a href="{% url 'user:u-friends-list' profile.user.username %}" class="friends_list"> <button>FRIENDS LIST</button> </a> 
            </div>
          </nav>
        </div>
      </div>
    </div>
  </body>
</html>